name: eda
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - protobuf==3.20.*
      - pandas==1.2.3
      - requests==2.24.0
      - jupyterlab==3.0.12
      - seaborn==0.11.1
      - pandas-profiling==3.1.0
      - pyarrow==2.0
