name: data_check
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - protobuf==3.20.*
      - pandas==1.2.3
      - pytest==6.2.2
      - scipy==1.5.2
      
