name: nyc_airbnb_dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.6
  - pip=20.3.3
  - git=2.30.2
  - pip:
      - wandb==0.13.2
      - mlflow==2.2.2
      - protobuf==3.20.*
      - ipython==7.21.0
      - notebook==6.2.0
      - jupyterlab==3.0.10
      - cookiecutter==1.7.2
      - hydra-core==1.0.6
      - matplotlib==3.3.4
      - pandas==1.2.3
      
      

      #conda env create -f environment.yml
      #conda remove -n nyc_airbnb_dev --all