name: download_file
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - mlflow==2.2.2
      - protobuf==3.20.*
      - pandas==1.2.3
      - requests==2.24.0
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
